# Generated by Django 3.1.2 on 2020-11-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='user',
        ),
    ]
