# Generated by Django 3.1.2 on 2020-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='antes de tener titulo', max_length=100),
            preserve_default=False,
        ),
    ]
