# Generated by Django 3.1.2 on 2020-11-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='userId',
            new_name='user',
        ),
    ]
