# Generated by Django 3.1.2 on 2020-11-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='isAdmin',
            new_name='is_admin',
        ),
    ]
